name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Prepare deployment
        run: |
          # Copy built files to root
          cp -r dist/* .
          
          # Ensure .nojekyll and CNAME are in root
          touch .nojekyll
          echo "www.candeacandles.com" > CNAME
          
          # Remove source files to keep only production files
          rm -rf src
          rm -rf node_modules
          rm -rf dist
          rm -f *.ts *.json *.js *.md
          rm -rf .github
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
